### ISSUE TITLE
Missing JUnit dependency

### ISSUE THREAD

**Issue by AntonisGkortzis** [stomaras/unit_testing-#1]
https://github.com/stomaras/unit_testing/blob/5525230c6804d018db9ef07dca4ea32891f94156/pom.xml#L1

The junit dependency is missing from your POM xml thus, the test are not runnable.. 
Did you try to run the tests before sending the exercise?? 

Please add the ```4.12``` version of the junit dependency.

**Comment by stomaras** [comment]
Antonis i add the 4.12 version
