### ISSUE TITLE
Misplaced test files

### ISSUE THREAD

**Issue by AntonisGkortzis** [stomaras/unit_testing-#3]
https://github.com/stomaras/unit_testing/blob/5525230c6804d018db9ef07dca4ea32891f94156/grades.txt#L1

Test file should be located in ```src/test/resources```. Create this directory and place the grade files there.
Don't forget to update their paths wherever you have used them.

PS. Since you already have this directory and the file, you should only remove the one in your base directory.

**Comment by stomaras** [comment]
Antonis, the file is in this path I did
